# Generated by Django 5.2.3 on 2025-06-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='price',
            new_name='age',
        ),
    ]
